[package]
name = "egui_graph"
version = "0.1.0"
edition = "2018"

# Required for wgpu v0.10 feature resolution.
resolver = "2"

[dependencies]
egui = "0.20.0"

[dev-dependencies]
bevy = "0.9.0"
bevy_egui = "0.19"
petgraph = "0.6"
